./avctl run src/backend/tools:download_data -- -- --data_source=av \
--mission-id=8726561667573623653_7065208030780651043 \
--min-time-ns=1749829273241831000 \
--max-time-ns=1749829542000029000 \
--output_dir_name="/home/ubuntu/lyftbags/tmpoc_tol" \
--topics=/arene/localization/ensd_localization,\
/arene/perception/perception_online_local_map,\
/avs/screenshot_webp,\
/avs/slog_events,\
/calibration,\
/compressed_semantic_map,\
/compressed_semantic_map_ensd,\
/control/controller_command_viz,\
/control/driver_controls,\
/control/envelope_controller_command,\
/control/envelope_controller_data,\
/denso_radar_flr_observations,\
/arene/perception/perception_tracks,\
/denso_radar_flr_observations_points,\
/denso_radar_frd_observations,\
/denso_radar_frr_observations,\
/denso_radar_frr_observations_points,\
/denso_radar_rlr_observations,\
/denso_radar_rlr_observations_points,\
/denso_radar_rrr_observations,\
/denso_radar_rrr_observations_points,\
/front_camera_alias,\
/front_pvm/image_frame,\
/arene/perception/prediction_obstacles,\
/front_pvm/image_frame_webp,\
/front_tele/image_frame,\
/front_tele/image_frame_webp,\
/front_wide/image_frame,\
/front_wide/image_frame_webp,\
/left_side_forward/image_frame,\
/left_side_forward/image_frame_webp,\
/left_side_pvm/image_frame,\
/left_side_pvm/image_frame_webp,\
/left_side_rearward/image_frame,\
/arene/perception/traffic_light_output,\
/left_side_rearward/image_frame_webp,\
/local_projection,\
/localization/motion_state_local,\
/localization/transform_local_ecef,\
/map_fusion/map_fusion_debug_message,\
/map_fusion/map_fusion_debug_message_viz,\
/map/map_id,\
/map/map_id_ensd,\
/map/route_name,\
/novatel/gnsspos,\
/avs/config,\
/novatel/inspva,\
/perception/spindata,\
/perception/spindata_nova,\
/planning,\
/planning/lane_change_status_output,\
/planning/local_scene_debug_adas_ecu,\
/planning/planner_context,\
/planning/planner_visualization,\
/planning/trajectory_candidates,\
/planning/trajectory_planning_problem,\
/avs/mission,\
/planning/turn_indicator_output,\
/rear_pvm/image_frame,\
/rear_pvm/image_frame_webp,\
/rear_tele/image_frame,\
/rear_tele/image_frame_webp,\
/right_side_forward/image_frame,\
/right_side_forward/image_frame_webp,\
/right_side_pvm/image_frame,\
/right_side_pvm/image_frame_webp,\
/right_side_rearward/image_frame,\
/avs/reflection,\
/right_side_rearward/image_frame_webp,\
/scope_manager/feature_scope,\
/scope_manager/obstacle_risk,\
/ublox/navsol,\
/ublox/navsvinfo,\
/vehicle_report/autonomy_event,\
/vehicle_report/autonomy_state,\
/vehicle_report/gear,\
/vehicle_report/is_stationary,\
/vehicle_report/speed,\
/avs/screenshot,\
/vehicle_report/steering,\
/vehicle_report/turn_indicator_stalk_report,\
/vehicle_report/vehicle_state_summary,\
/vehicle_report/wheel_speed
